# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

platform :android do
  desc "Deploy to Firebase app distribution"
  lane :distribute do
    firebase_app_distribution(
      groups: "tester",
      release_notes: "Fixing bug in features",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: "1//0gAVUcW-y4c53CgYIARAAGBASNwF-L9IrFunb54riCxMzefi3qqYaQHA1-Te7DSttr80wwOuMlWgzNopJ__pG83n-h1IwZb_926A",
      app: "1:658184514993:android:2110b45a72040b731e2190"
     )
  end
end
